#!/usr/bin/env python3
"""Plot BuilderBench CRL/TD3/TD-InfoNCE success for density-estimator ablations.

Default mode refreshes C3T1, C4T1, and C5T3 (two figures per task: crl10 and
crl25). C5T2 and C7T2 remain available via ``--tasks``. C7T2 is crl10-only
(Warp CRL dual-dgr + TD-InfoNCE, historical TD3). Each figure compares three
estimators using all available seeds (mean ± SEM). Training success is
unsmoothed. Eval success shows faint raw values and a bold centered rolling
mean over five eval checkpoints.

Legacy C4T2 combined 10-vs-25 figures are preserved behind --legacy-c4t2
and are not regenerated by default.
"""
from __future__ import annotations

import argparse
import os
import re
import sys

sys.path.insert(0, os.path.dirname(__file__))
import plot_builderbench_train_success1000 as base  # noqa: E402

import matplotlib

matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker

LOG_ROOT = '/n/fs/mislresearch/sgcrl/logs'
RUN_ROOT = 'final_runs/other_density_estimators'
OUT_DIR = (
    '/n/fs/mislresearch/sgcrl/figs/builderbench/final_runs/'
    'other_density_estimators'
)
MIN_FINAL_STEP = 190_000_000
EXPECTED_SEEDS = 2

REFRESH_TASKS = (
    'creative3_task1',
    'creative4_task1',
    'creative5_task3',
)

CRL_SUFFIX = {
    10: '_ep50_200m_crl10_eval10_warp_2h30',
    25: '_ep50_200m_crl25_eval10_warp_4h',
}

C5_CRL_SUFFIX = {
    10: '_ep70_200m_crl10_eval10_warp_2h30',
    25: '_ep70_200m_crl25_eval10_warp_4h',
}

ESTIMATORS = (
    ('CRL', '#E8834C'),
    ('TD3', '#4CE87A'),
    ('TD-InfoNCE', '#E84C6F'),
)

TASK_RUN_STEMS = {
    'creative3_task1': {
        'CRL': (
            'ppo_builderbench_creative3_task1_e1024_pd_crl_tau05_'
            'catselect_extrew1'
        ),
        'TD3': (
            'ppo_builderbench_creative3_task1_e1024_pd_td3_logq_tau05_'
            'catselect_extrew1'
        ),
        'TD-InfoNCE': (
            'ppo_builderbench_creative3_task1_e1024_pd_tdinfonce_tau05_'
            'catselect'
        ),
    },
    'creative4_task1': {
        'CRL': (
            'ppo_builderbench_creative4_task1_e1024_pd_crl_tau05_actorreset_'
            'nopermute_norand_normobs_catselect_minstd1e4_extrew1'
        ),
        'TD3': (
            'ppo_builderbench_creative4_task1_e1024_pd_td3_logq_tau05_'
            'actorreset_nopermute_catselect_minstd1e4_fixedx01_extrew1'
        ),
        'TD-InfoNCE': (
            'ppo_builderbench_creative4_task1_e1024_pd_tdinfonce_tau05_'
            'actorreset_nopermute_catselect_minstd1e4_extrew1'
        ),
    },
    'creative5_task2': {
        'CRL': (
            'ppo_builderbench_creative5_task2_e1024_pd_crl_tau05_actorreset_'
            'evalvid_catselect_extrew1'
        ),
        'TD3': (
            'ppo_builderbench_creative5_task2_e1024_pd_td3_logq_tau05_'
            'actorreset_nopermute_normobs_evalvid_catselect'
        ),
        'TD-InfoNCE': (
            'ppo_builderbench_creative5_task2_e1024_pd_tdinfonce_tau05_'
            'catselect_extrew1'
        ),
    },
    'creative5_task3': {
        'CRL': (
            'ppo_builderbench_creative5_task3_e1024_pd_crl_tau05_actorreset_'
            'nopermute_norand_normobs_evalvid_catselect_extrew1'
        ),
        'TD3': (
            'ppo_builderbench_creative5_task3_e1024_pd_td3_logq_tau05_'
            'actorreset_permute_rand_evalvid_catselect_extrew1'
        ),
        'TD-InfoNCE': (
            'ppo_builderbench_creative5_task3_e1024_pd_tdinfonce_tau05_'
            'catselect_extrew1'
        ),
    },
    'creative7_task2': {
        'CRL': (
            'final_runs/'
            'ppo_builderbench_creative7_task2_e1024_pd_crl_tau05_'
            'nopermute_fixedx01_catwp_extrew1_minstd1e5_entanneal_ep60_'
            '200m_crl10_dualgradreg_c100_lamlr1e2_valuedgr_c100_'
            'lamlr1e6_warp_2h30'
        ),
        'TD3': (
            'ppo_builderbench_creative7_task2_e1024_pd_td3_logq_tau05_'
            'actorreset_nopermute_normobs_evalvid_catwp_tol0013'
        ),
        'TD-InfoNCE': (
            'final_runs/'
            'ppo_builderbench_creative7_task2_e1024_pd_tdinfonce_tau05_'
            'nopermute_fixedx01_catwp_extrew1_minstd1e5_entanneal_ep60_'
            '200m_crl10_warp_2h30'
        ),
    },
}

TASK_DIRECT_PATHS = frozenset({'creative7_task2'})
C7_CRL_STEPS = (10,)

LEGACY_C4T2_RUNS = [
    (
        'CRL · 10 updates',
        'ppo_builderbench_creative4_task2_e1024_pd_crl_tau05_catselect_'
        'stateonly_extrew1_ep50_200m_crl10_eval10_warp_2h30',
        '#E8834C',
        '-',
    ),
    (
        'CRL · 25 updates',
        'ppo_builderbench_creative4_task2_e1024_pd_crl_tau05_catselect_'
        'stateonly_extrew1_ep50_200m_crl25_eval10_warp_4h',
        '#E8834C',
        '--',
    ),
    (
        'TD3 · 10 updates',
        'ppo_builderbench_creative4_task2_e1024_pd_td3_logq_tau05_'
        'catselect_extrew1_ep50_200m_crl10_eval10_warp_2h30',
        '#4CE87A',
        '-',
    ),
    (
        'TD3 · 25 updates',
        'ppo_builderbench_creative4_task2_e1024_pd_td3_logq_tau05_'
        'catselect_extrew1_ep50_200m_crl25_eval10_warp_4h',
        '#4CE87A',
        '--',
    ),
    (
        'TD-InfoNCE · 10 updates',
        'ppo_builderbench_creative4_task2_e1024_pd_tdinfonce_tau05_'
        'catselect_extrew1_ep50_200m_crl10_eval10_warp_2h30',
        '#E84C6F',
        '-',
    ),
    (
        'TD-InfoNCE · 25 updates',
        'ppo_builderbench_creative4_task2_e1024_pd_tdinfonce_tau05_'
        'catselect_extrew1_ep50_200m_crl25_eval10_warp_4h',
        '#E84C6F',
        '--',
    ),
]


def _run_stem(task: str, estimator: str, crl_steps: int) -> str:
  if task == 'creative7_task2':
    if crl_steps not in C7_CRL_STEPS:
      raise RuntimeError(f'c7t2 only has crl10 runs, got crl{crl_steps}')
    return TASK_RUN_STEMS[task][estimator]
  suffixes = C5_CRL_SUFFIX if task in {
      'creative5_task2', 'creative5_task3'} else CRL_SUFFIX
  return TASK_RUN_STEMS[task][estimator] + suffixes[crl_steps]


def _run_path(run_stem: str, task: str | None = None) -> str:
  if task in TASK_DIRECT_PATHS or run_stem.startswith('final_runs/'):
    return run_stem
  return f'{RUN_ROOT}/{run_stem}'


def _seed_final_steps(seed_series: list[list[tuple[int, float]]]) -> list[int]:
  finals = []
  for pts in seed_series:
    if not pts:
      continue
    finals.append(int(pts[-1][0]))
  return finals


def _truncate_seed_series(
    seed_series: list[list[tuple[int, float]]], horizon: int,
) -> list[list[tuple[int, float]]]:
  out: list[list[tuple[int, float]]] = []
  for pts in seed_series:
    clipped = [(int(x), float(y)) for x, y in pts if int(x) <= horizon]
    if clipped and clipped[-1][0] < horizon:
      clipped.append((horizon, clipped[-1][1]))
    if clipped:
      out.append(clipped)
  return out


def _common_horizon(
    train_by_estimator: dict[str, list[list[tuple[int, float]]]],
    eval_by_estimator: dict[str, list[list[tuple[int, float]]]],
) -> int:
  finals: list[int] = []
  for seed_series in train_by_estimator.values():
    finals.extend(_seed_final_steps(seed_series))
  for seed_series in eval_by_estimator.values():
    finals.extend(_seed_final_steps(seed_series))
  if not finals:
    raise RuntimeError('no trajectory data found for panel')
  return min(finals)


def _task_display_name(task: str) -> str:
  match = re.fullmatch(r'creative(\d+)_task(\d+)', task)
  if not match:
    return f'BuilderBench {task}'
  return f'BuilderBench Creative {match.group(1)} Task {match.group(2)}'


def _plot_band(ax, xs, mean, se, color, *, smooth: bool) -> None:
  if not any(v > 0 for v in se):
    return
  lo = [m - s for m, s in zip(mean, se)]
  hi = [m + s for m, s in zip(mean, se)]
  if smooth:
    lo = base._rolling_mean(lo, base.EVAL_SMOOTH_WINDOW)
    hi = base._rolling_mean(hi, base.EVAL_SMOOTH_WINDOW)
  ax.fill_between(xs, lo, hi, color=color, alpha=0.16, linewidth=0)


def _load_panel_data(
    task: str, crl_steps: int,
) -> tuple[
    dict[str, list[list[tuple[int, float]]]],
    dict[str, list[list[tuple[int, float]]]],
]:
  train_by_estimator: dict[str, list[list[tuple[int, float]]]] = {}
  eval_by_estimator: dict[str, list[list[tuple[int, float]]]] = {}
  for label, _color in ESTIMATORS:
    run_stem = _run_stem(task, label, crl_steps)
    run_path = _run_path(run_stem, task)
    train_series = base._read_train_seed_series(LOG_ROOT, run_path)
    eval_series = base._read_eval_seed_series(LOG_ROOT, run_path)
    if not train_series or len(train_series) != len(eval_series):
      raise RuntimeError(
          f'{task} {label} crl{crl_steps}: train/eval seed mismatch '
          f'(train={len(train_series)}, eval={len(eval_series)}) '
          f'({run_stem})')
    train_by_estimator[label] = train_series
    eval_by_estimator[label] = eval_series
  seed_counts = {
      label: len(series) for label, series in train_by_estimator.items()
  }
  if task not in TASK_DIRECT_PATHS and len(set(seed_counts.values())) != 1:
    raise RuntimeError(
        f'{task} crl{crl_steps}: estimator seed counts differ '
        f'({seed_counts})')
  return train_by_estimator, eval_by_estimator


def _plot_task_panel(
    task: str,
    crl_steps: int,
    *,
    allow_partial: bool,
    min_final_step: int,
) -> None:
  train_by_estimator, eval_by_estimator = _load_panel_data(task, crl_steps)
  if task in TASK_DIRECT_PATHS:
    # Historical TD3 is a failed/short pick; do not clip live CRL/TDI to it.
    horizon = max(
        max(_seed_final_steps(s) or [0])
        for s in list(train_by_estimator.values())
        + list(eval_by_estimator.values())
    )
  else:
    horizon = _common_horizon(train_by_estimator, eval_by_estimator)
  is_partial = horizon < min_final_step
  if is_partial and not allow_partial:
    raise RuntimeError(
        f'{task} crl{crl_steps}: common horizon {horizon} < '
        f'{min_final_step}; pass --allow-partial to plot truncated panel')

  if task not in TASK_DIRECT_PATHS:
    train_by_estimator = {
        label: _truncate_seed_series(series, horizon)
        for label, series in train_by_estimator.items()
    }
    eval_by_estimator = {
        label: _truncate_seed_series(series, horizon)
        for label, series in eval_by_estimator.items()
    }

  fig, axes = plt.subplots(1, 2, figsize=(14.5, 5.0), sharey=True)
  summaries = []

  for label, color in ESTIMATORS:
    tx, tm, tse, tn = base._aggregate_mean_stderr(
        train_by_estimator[label])
    ex, em, ese, en = base._aggregate_mean_stderr(
        eval_by_estimator[label])

    if tn != en:
      raise RuntimeError(
          f'{task} {label} crl{crl_steps}: train/eval mismatch after '
          f'truncation, found train={tn}, eval={en}')

    tx, tm, tse = base._subsample_curve(tx, tm, tse, max_pts=600)
    ex, em, ese = base._subsample_curve(ex, em, ese, max_pts=600)

    curve_label = f'{label} (n={tn})'
    axes[0].plot(
        tx, tm, color=color, linestyle='-', linewidth=2.2, label=curve_label)
    _plot_band(axes[0], tx, tm, tse, color, smooth=False)

    eval_smoothed = base._plot_eval_smoothed(
        axes[1], ex, em, color=color, label=curve_label,
        linestyle='-', linewidth=2.2,
        window=base.EVAL_SMOOTH_WINDOW)
    _plot_band(axes[1], ex, em, ese, color, smooth=True)

    seed_train_finals = _seed_final_steps(train_by_estimator[label])
    summaries.append(
        f'{label}: final train={tm[-1]:.3f}, '
        f'final eval MA={eval_smoothed[-1]:.3f}, '
        f'seed train max={seed_train_finals}')

  eval_panel_title = (
      f'Eval success (centered rolling mean, window='
      f'{base.EVAL_SMOOTH_WINDOW})')
  if is_partial:
    status_line = (
        f'PARTIAL · common horizon = {base._fmt_steps(horizon, None)} env '
        f'steps (< {base._fmt_steps(min_final_step, None)})')
  else:
    status_line = 'complete · 200M env steps'
  eval_panel_title += f'\n{status_line}'

  for ax, panel_title in zip(
      axes,
      (
          'Train success (1000 episodes; unsmoothed)',
          eval_panel_title,
      ),
  ):
    ax.set_title(panel_title, fontsize=11, fontweight='bold', pad=10)
    ax.set_xlabel('environment steps')
    ax.set_ylim(-0.05, 1.05)
    ax.set_xlim(0, horizon)
    ax.xaxis.set_major_formatter(mticker.FuncFormatter(base._fmt_steps))
    ax.grid(axis='y', linestyle='--', alpha=0.4)
    ax.spines[['top', 'right']].set_visible(False)
  axes[0].set_ylabel('success')

  title_main = (
      f'{_task_display_name(task)} — density estimators · '
      f'{crl_steps} updates/iter')

  handles, labels = axes[1].get_legend_handles_labels()
  legend = axes[1].legend(
      handles, labels, loc='upper left', bbox_to_anchor=(1.02, 1.0),
      fontsize=9, framealpha=1.0, edgecolor='#333333', fancybox=False,
      handlelength=2.7)
  fig.subplots_adjust(left=0.07, right=0.88, top=0.80, bottom=0.14, wspace=0.22)
  fig.suptitle(title_main, fontsize=13, fontweight='bold', y=0.96)

  filename = f'{task}_crl_td3_tdinfonce_crl{crl_steps}_success.png'
  out = os.path.join(OUT_DIR, filename)
  fig.savefig(
      out, dpi=170, bbox_inches='tight', bbox_extra_artists=(legend,),
      pad_inches=0.18, facecolor='white')
  plt.close(fig)

  status = 'PARTIAL' if is_partial else 'COMPLETE'
  print(f'wrote {out} [{status}; common_horizon={horizon}]')
  for summary in summaries:
    print(f'  {summary}')


def _plot_legacy_c4t2_comparison(
    runs, *, title: str, filename: str, min_final_step: int,
) -> None:
  fig, axes = plt.subplots(1, 2, figsize=(14.5, 5.0), sharey=True)
  summaries = []

  for label, run, color, linestyle in runs:
    run_path = _run_path(run)
    train_series = base._read_train_seed_series(LOG_ROOT, run_path)
    eval_series = base._read_eval_seed_series(LOG_ROOT, run_path)
    tx, tm, tse, tn = base._aggregate_mean_stderr(train_series)
    ex, em, ese, en = base._aggregate_mean_stderr(eval_series)

    if tn != EXPECTED_SEEDS or en != EXPECTED_SEEDS:
      raise RuntimeError(
          f'{label}: expected two train/eval seeds, found train={tn}, '
          f'eval={en}')
    if not tx or tx[-1] < min_final_step:
      raise RuntimeError(
          f'{label}: incomplete training horizon '
          f'({tx[-1] if tx else "no data"})')

    tx, tm, tse = base._subsample_curve(tx, tm, tse, max_pts=600)
    axes[0].plot(
        tx, tm, color=color, linestyle=linestyle, linewidth=2.2,
        label=f'{label} (n={EXPECTED_SEEDS})')
    _plot_band(axes[0], tx, tm, tse, color, smooth=False)

    eval_smoothed = base._plot_eval_smoothed(
        axes[1], ex, em, color=color, label=f'{label} (n={EXPECTED_SEEDS})',
        linestyle=linestyle, linewidth=2.2,
        window=base.EVAL_SMOOTH_WINDOW)
    _plot_band(axes[1], ex, em, ese, color, smooth=True)

    summaries.append(
        f'{label}: final train={tm[-1]:.3f}, '
        f'final eval MA={eval_smoothed[-1]:.3f}, max_step={tx[-1]}')

  for ax, panel_title in zip(
      axes,
      (
          'Train success (1000 episodes; unsmoothed)',
          f'Eval success (centered rolling mean, window='
          f'{base.EVAL_SMOOTH_WINDOW})',
      ),
  ):
    ax.set_title(panel_title, fontsize=11, fontweight='bold')
    ax.set_xlabel('environment steps')
    ax.set_ylim(-0.05, 1.05)
    ax.xaxis.set_major_formatter(mticker.FuncFormatter(base._fmt_steps))
    ax.grid(axis='y', linestyle='--', alpha=0.4)
    ax.spines[['top', 'right']].set_visible(False)
  axes[0].set_ylabel('success')

  handles, labels = axes[1].get_legend_handles_labels()
  legend = axes[1].legend(
      handles, labels, loc='upper left', bbox_to_anchor=(1.02, 1.0),
      fontsize=9, framealpha=1.0, edgecolor='#333333', fancybox=False,
      handlelength=2.7)
  fig.suptitle(title, fontsize=13, fontweight='bold', y=1.02)
  fig.tight_layout(rect=(0, 0, 0.88, 0.98))

  out = os.path.join(OUT_DIR, filename)
  fig.savefig(
      out, dpi=170, bbox_inches='tight', bbox_extra_artists=(legend,),
      facecolor='white')
  plt.close(fig)
  print(f'wrote {out}')
  for summary in summaries:
    print(f'  {summary}')


def _plot_legacy_c4t2(min_final_step: int) -> None:
  _plot_legacy_c4t2_comparison(
      LEGACY_C4T2_RUNS,
      title='BuilderBench Creative 4 Task 2 — density-estimator comparison',
      filename=(
          'creative4_task2_crl_td3_tdinfonce_'
          'crl10_vs_crl25_success.png'),
      min_final_step=min_final_step,
  )
  for method, runs in (
      ('CRL', LEGACY_C4T2_RUNS[0:2]),
      ('TD3', LEGACY_C4T2_RUNS[2:4]),
      ('TD-InfoNCE', LEGACY_C4T2_RUNS[4:6]),
  ):
    slug = method.lower().replace('-', '')
    _plot_legacy_c4t2_comparison(
        runs,
        title=(
            f'BuilderBench Creative 4 Task 2 — {method}: '
            '10 vs 25 updates'),
        filename=(
            f'creative4_task2_{slug}_crl10_vs_crl25_success.png'),
        min_final_step=min_final_step,
    )


def _parse_args() -> argparse.Namespace:
  parser = argparse.ArgumentParser(
      description=(
          'Plot BuilderBench other-density-estimator success curves. '
          'Default refreshes C3T1/C4T1/C5T3 only; C5T2 is opt-in because '
          'its current update-count panels are incomplete.'
      ))
  parser.add_argument(
      '--tasks', nargs='+', default=list(REFRESH_TASKS),
      choices=sorted(TASK_RUN_STEMS),
      help=(
          'Tasks to refresh (default: C3T1, C4T1, C5T3). Explicit C5T2 '
          'requires complete three-estimator data for each requested count.'
      ),
  )
  parser.add_argument(
      '--crl-steps', nargs='+', type=int, default=[10, 25],
      choices=sorted(CRL_SUFFIX),
      help='Density-update counts per PPO iteration (default: 10 25).',
  )
  parser.add_argument(
      '--allow-partial', action='store_true',
      help=(
          'Plot incomplete panels by truncating all curves to the common '
          'fair horizon and marking the figure PARTIAL.'
      ),
  )
  parser.add_argument(
      '--min-final-step', type=int, default=MIN_FINAL_STEP,
      help=f'Completion threshold in env steps (default: {MIN_FINAL_STEP}).',
  )
  parser.add_argument(
      '--legacy-c4t2', action='store_true',
      help='Also regenerate legacy C4T2 combined 10-vs-25 figures.',
  )
  parser.add_argument(
      '--out-dir', default=OUT_DIR,
      help='Output directory for PNG figures.',
  )
  return parser.parse_args()


def main() -> None:
  args = _parse_args()
  global OUT_DIR
  OUT_DIR = args.out_dir
  os.makedirs(OUT_DIR, exist_ok=True)

  for task in args.tasks:
    steps = C7_CRL_STEPS if task == 'creative7_task2' else args.crl_steps
    for crl_steps in steps:
      _plot_task_panel(
          task,
          crl_steps,
          allow_partial=args.allow_partial,
          min_final_step=args.min_final_step,
      )

  if args.legacy_c4t2:
    _plot_legacy_c4t2(args.min_final_step)


if __name__ == '__main__':
  main()
